# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('tags', models.TextField()),
                ('inventory_quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
