# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
