# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170418_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tags',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_quantity',
        ),
    ]
